# features used for predictions  
#'Nitrate' has got to be in here for now
feat_list: ['Nitrate','Discharge_l10','Precip','TempMax','TempMin','SolarRad']
#are static features used
static_features_used: True
static_features: [ "NLCD_AG",
                    "NLCD_FOR",            
                    "NO3_DOM",             
                    "TILE_DRAIN",         
                    "TOT_ARTIFICIAL",     
                    "TOT_BASIN_AREA",      
                    "TOT_CANALDITCH",     
                    "TOT_CONTACT",         
                    "TOT_CWD",             
                    "TOT_ET",             
                    "TOT_HGAD",            
                    "TOT_HGB",             
                    "TOT_HGBD",            
                    "TOT_HGC",             
                    "TOT_LAKEPOND",       
                    "TOT_N97",             
                    "TOT_NDAMS2013",       
                    "TOT_NID_STORAGE2013", 
                    "TOT_NPDES_MAJ_DENS",  
                    "TOT_RH",             
                    "TOT_STREAM_LENGTH",   
                    "TOT_STRM_DENS",       
                    "TOT_WDANN",           
                    "TRANSM",              
                    "UNSAT_TT",           
                    "WCON",                
                    "fert_uN_mt_sqkm"]
#sequence length
seq_len: 180
#train fraction
trn_frac: 0.5625
#validation fraction 
val_frac: 0.1875 
#testing fraction
test_frac: 0.25
#number of features used
num_features: 53   
learning_rate: 0.005
num_epochs: 64
batch_size: 512
#number of layers
num_layers: 2
#dropout fraction
dropout: 0
#weight decay for optimizer
weight_decay: 0.001
#number of cells
hidden_size: 20
#should input data be shuffled
shuffle: True
#use existing data that has been prepared
use_exisiting_data: True
#when do you want to predict, two options are "train_val" and "full"
#if "full" is chosen then the model will be trained with the sum of trn_frac
# and val_frac
predict_period: 'full'