#model run config location
config_loc: '03_model/multi_site_model_config.yaml'
#location of data
netcdf_loc: '02_munge/out/model_input_rolling.nc'
#list of sites
site_info_loc: '04_analysis/out/basin_char_w_clusters_hydroterranes_230208.csv'
#read in pretrained weights to make predictions
weights_dir: ''

#input file location
read_input_data_from_file: False
input_file_loc : None

model_run_id : 'Run_07_MS_OOS_230208'
n_reps: 2


train_model : True
save_results_csv : True
hp_tune : False
hp_tune_vals : {}
fine_tune : False

#TRUE/FALSE for if the models should be trained for oos experiments
train_oos_exp: True


#%%
oos_sites : os.path.join('03_model/out/multi_site/Run_07_OOS','Rep_00','oos_sites.csv')
#site_no_list = oos_sites.site_no[0:2]
#station_nm_list = site_info[site_info.site_no.isin(site_no_list)].station_nm
#predict using the multi-site model
