#model run config location
config_loc: '03_model/single_site_model_config.yaml'
#location of data
netcdf_loc: '02_munge/out/model_input_rolling.nc'
#list of sites
site_info_loc: '04_analysis/out/basin_char_w_clusters_hydroterranes_221005.csv'
#read in pretrained weights to make predictions
weights_dir: ''

#input file location
read_input_data_from_file: False
input_file_loc : None
save_results_csv: True

model_run_id : 'Run_00_HP_TESTRUN_01'
n_reps: 2


train_model : True
save_results_csv : True
#do hyperparameter tuning
hp_tune : True
#tune across these values
#sequence length
sl : [20,60,180]
#learning rate
#lr : [0.005,0.001]
lr : [0.1, 0.5]
#number of layers
l : [1]
#l : [1,2,4]
#number of cells
#ncl : [10,20,40]
ncl : [2]

#fine tune for transfer learning
fine_tune : False


